// =============================================================================
// PDF Report Builder — generates PDF from artifact data using jsPDF
// Lazy-loaded to avoid bloating the initial bundle.
// =============================================================================

import type { AgentArtifact } from '@/hooks/useAIAgent';

/** Sanitize title into a filename stem. */
function toFilename(title: string): string {
    return (title || 'report')
        .replace(/[^a-zA-Z0-9_\- ]/g, '')
        .replace(/\s+/g, '_')
        .slice(0, 60);
}

// ─── Colors ──────────────────────────────────────────────────────────────────

const C = {
    fg: [24, 24, 27] as [number, number, number],
    muted: [113, 113, 122] as [number, number, number],
    accent: [37, 99, 235] as [number, number, number],
    green: [22, 163, 74] as [number, number, number],
    amber: [217, 119, 6] as [number, number, number],
    red: [220, 38, 38] as [number, number, number],
    bg: [250, 250, 250] as [number, number, number],
    headerBg: [241, 241, 241] as [number, number, number],
};

// ─── Builder ─────────────────────────────────────────────────────────────────

export async function exportPdf(artifact: AgentArtifact, title?: string): Promise<void> {
    const { default: jsPDF } = await import('jspdf');
    const { applyPlugin } = await import('jspdf-autotable');
    applyPlugin(jsPDF);

    const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 40;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    // ── Helpers ───────────────────────────────────────────────────────────
    const addText = (text: string, opts: { size?: number; color?: [number, number, number]; bold?: boolean; maxWidth?: number } = {}) => {
        const { size = 10, color = C.fg, bold = false, maxWidth = contentWidth } = opts;
        doc.setFontSize(size);
        doc.setTextColor(...color);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        const lines = doc.splitTextToSize(text, maxWidth);
        const lineHeight = size * 1.4;
        for (const line of lines) {
            if (y + lineHeight > doc.internal.pageSize.getHeight() - margin) {
                doc.addPage();
                y = margin;
            }
            doc.text(line, margin, y);
            y += lineHeight;
        }
    };

    const addGap = (pts: number) => { y += pts; };

    const addAutoTable = (head: string[][], body: string[][]) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).autoTable({
            startY: y,
            margin: { left: margin, right: margin },
            head,
            body,
            styles: { fontSize: 8, cellPadding: 4, textColor: C.fg, lineColor: [228, 228, 231], lineWidth: 0.5 },
            headStyles: { fillColor: C.headerBg, textColor: C.muted, fontStyle: 'bold', fontSize: 7 },
            alternateRowStyles: { fillColor: [250, 250, 250] },
            didDrawPage: () => { /* keep y updated */ },
        });
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        y = (doc as any).lastAutoTable.finalY + 12;
    };

    const str = (v: unknown): string => (v === null || v === undefined ? '' : String(v));

    // ── Title ─────────────────────────────────────────────────────────────
    const artType = artifact.type as string;
    const reportTitle = title || artifact.title || artType.charAt(0).toUpperCase() + artType.slice(1) + ' Report';

    addText(reportTitle, { size: 16, bold: true });
    addGap(2);
    addText(`Generated by Resona AI · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`, { size: 8, color: C.muted });
    addGap(16);

    // ── Body per artifact type ────────────────────────────────────────────
    switch (artType) {
        case 'stats': {
            const stats = artifact.stats ?? [];
            addText(`${artifact.totalRows != null ? artifact.totalRows.toLocaleString() + ' total rows, ' : ''}${stats.length} columns analyzed`, { size: 9, color: C.muted });
            addGap(8);
            addAutoTable(
                [['Column', 'Type', 'Distinct', 'Null %', 'Min', 'Max', 'Avg', 'Flags']],
                stats.map(s => [
                    s.name,
                    s.dataType,
                    String(s.distinctCount),
                    s.nullPercent.toFixed(1) + '%',
                    str(s.min),
                    str(s.max),
                    s.avg !== null ? String(s.avg) : '',
                    [s.isPrimaryKey && 'PK', s.isIndexed && 'IDX', s.nullable && 'NULL'].filter(Boolean).join(', '),
                ]),
            );
            break;
        }

        case 'anomalies': {
            const anomalies = artifact.anomalies ?? [];
            addText(`${artifact.totalAnomalies ?? anomalies.length} anomal${(artifact.totalAnomalies ?? anomalies.length) === 1 ? 'y' : 'ies'} across ${artifact.scannedColumns ?? 0} columns`, { size: 9, color: C.muted });
            addGap(8);
            if (anomalies.length > 0) {
                addAutoTable(
                    [['Column', 'Type', 'Severity', 'Count', 'Detail']],
                    anomalies.map(a => [a.column, a.type.replace(/_/g, ' '), a.severity.toUpperCase(), String(a.count), a.explanation]),
                );
            }
            break;
        }

        case 'quality': {
            const score = artifact.score ?? 0;
            const scoreColor = score >= 80 ? C.green : score >= 50 ? C.amber : C.red;
            addText(String(score), { size: 36, bold: true, color: scoreColor });
            addText('/100', { size: 12, color: C.muted });
            addGap(4);

            // Score bar
            doc.setFillColor(...C.headerBg);
            doc.roundedRect(margin, y, contentWidth, 6, 3, 3, 'F');
            doc.setFillColor(...scoreColor);
            doc.roundedRect(margin, y, contentWidth * (score / 100), 6, 3, 3, 'F');
            y += 16;

            if (artifact.summary) {
                addText(artifact.summary, { size: 9, color: C.muted });
                addGap(8);
            }
            const issues = artifact.issues ?? [];
            if (issues.length > 0) {
                addAutoTable(
                    [['Severity', 'Column', 'Issue', 'Affected Rows', 'Recommendation']],
                    issues.map(i => [i.severity.toUpperCase(), i.column, i.issueType.replace(/_/g, ' '), String(i.affectedRows), i.recommendation]),
                );
            }
            break;
        }

        case 'joins': {
            const paths = artifact.paths ?? [];
            if (paths.length === 0) {
                addText('No join paths found.', { size: 9, color: C.muted });
            } else {
                addAutoTable(
                    [['From Table', 'From Column', 'To Table', 'To Column', 'Type', 'Confidence']],
                    paths.map(p => [p.from, p.fromColumn, p.to, p.toColumn, p.joinType === 'foreign_key' ? 'FK' : 'Heuristic', Math.round(p.confidence * 100) + '%']),
                );
            }
            break;
        }

        case 'metrics': {
            const groups = [
                { items: artifact.identifiers ?? [], label: 'Identifiers' },
                { items: artifact.dimensions ?? [], label: 'Dimensions' },
                { items: artifact.measures ?? [], label: 'Measures' },
                { items: artifact.timestamps ?? [], label: 'Timestamps' },
            ];
            for (const g of groups) {
                if (g.items.length === 0) continue;
                addText(g.label.toUpperCase(), { size: 8, bold: true, color: C.muted });
                addGap(2);
                addText(g.items.join('  ·  '), { size: 10, color: C.accent });
                addGap(10);
            }
            break;
        }

        default: {
            // Table artifact
            const rows = artifact.rows ?? [];
            const cols = artifact.columns ?? [];
            if (rows.length === 0 || cols.length === 0) {
                addText('No data.', { size: 9, color: C.muted });
            } else {
                addText(`${rows.length} row${rows.length !== 1 ? 's' : ''}, ${cols.length} column${cols.length !== 1 ? 's' : ''}`, { size: 9, color: C.muted });
                addGap(8);
                addAutoTable(
                    [cols.map(c => c.name)],
                    rows.map(row => cols.map(c => str(row[c.name]))),
                );
            }
            break;
        }
    }

    // ── SQL block ─────────────────────────────────────────────────────────
    if (artifact.sql) {
        addGap(8);
        addText('SQL', { size: 8, bold: true, color: C.muted });
        addGap(4);
        doc.setFillColor(245, 245, 245);
        const sqlLines = doc.splitTextToSize(artifact.sql, contentWidth - 16);
        const sqlH = sqlLines.length * 10 + 12;
        if (y + sqlH > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
        }
        doc.roundedRect(margin, y, contentWidth, sqlH, 4, 4, 'F');
        doc.setFontSize(7);
        doc.setFont('courier', 'normal');
        doc.setTextColor(...C.fg);
        doc.text(sqlLines, margin + 8, y + 10);
        y += sqlH + 8;
    }

    // ── Footer ────────────────────────────────────────────────────────────
    const pageCount = (doc as any).internal.getNumberOfPages ? (doc as any).internal.getNumberOfPages() : (doc as any).internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(...C.muted);
        doc.text('Resona AI · Schema Weaver Data Explorer', margin, doc.internal.pageSize.getHeight() - 20);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, doc.internal.pageSize.getHeight() - 20, { align: 'right' });
    }

    doc.save(`${toFilename(reportTitle)}.pdf`);
}

/**
 * Export an executive-summary PDF for table artifacts.
 * Shows key metrics, numeric highlights, categorical summary, and a data preview.
 */
export async function exportExecutivePdf(artifact: AgentArtifact, title?: string): Promise<void> {
    const { default: jsPDF } = await import('jspdf');
    const { applyPlugin } = await import('jspdf-autotable');
    applyPlugin(jsPDF);

    const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 40;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    const addText = (text: string, opts: { size?: number; color?: [number, number, number]; bold?: boolean; maxWidth?: number } = {}) => {
        const { size = 10, color = C.fg, bold = false, maxWidth = contentWidth } = opts;
        doc.setFontSize(size);
        doc.setTextColor(...color);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        const lines = doc.splitTextToSize(text, maxWidth);
        const lineHeight = size * 1.4;
        for (const line of lines) {
            if (y + lineHeight > doc.internal.pageSize.getHeight() - margin) {
                doc.addPage();
                y = margin;
            }
            doc.text(line, margin, y);
            y += lineHeight;
        }
    };

    const addGap = (pts: number) => { y += pts; };

    const addAutoTable = (head: string[][], body: string[][]) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).autoTable({
            startY: y,
            margin: { left: margin, right: margin },
            head,
            body,
            styles: { fontSize: 8, cellPadding: 4, textColor: C.fg, lineColor: [228, 228, 231], lineWidth: 0.5 },
            headStyles: { fillColor: C.headerBg, textColor: C.muted, fontStyle: 'bold', fontSize: 7 },
            alternateRowStyles: { fillColor: [250, 250, 250] },
        });
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        y = (doc as any).lastAutoTable.finalY + 12;
    };

    const str = (v: unknown): string => (v === null || v === undefined ? '' : String(v));

    const rows = artifact.rows ?? [];
    const cols = artifact.columns ?? [];
    const reportTitle = title || artifact.title || 'Executive Summary';

    // Title
    addText(reportTitle, { size: 16, bold: true });
    addGap(2);
    addText(`Executive Summary · Resona AI · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`, { size: 8, color: C.muted });
    addGap(20);

    // Key metrics
    const metricLine = [`${rows.length} rows`, `${cols.length} columns`];
    const numericCols = cols.filter(c => {
        const vals = rows.slice(0, 15).map(r => r[c.name]).filter(v => v !== null && v !== undefined);
        return vals.length > 0 && vals.every(v => !isNaN(Number(v)));
    });
    if (numericCols.length > 0) metricLine.push(`${numericCols.length} numeric`);
    addText(metricLine.join('  ·  '), { size: 12, bold: true, color: C.accent });
    addGap(16);

    // Numeric highlights
    if (numericCols.length > 0) {
        addText('NUMERIC HIGHLIGHTS', { size: 8, bold: true, color: C.muted });
        addGap(6);
        addAutoTable(
            [['Column', 'Min', 'Max', 'Avg', 'Sum']],
            numericCols.map(c => {
                const vals = rows.map(r => r[c.name]).filter(v => v !== null && v !== undefined).map(Number);
                const min = Math.min(...vals);
                const max = Math.max(...vals);
                const avg = vals.reduce((a, b) => a + b, 0) / vals.length;
                const sum = vals.reduce((a, b) => a + b, 0);
                return [c.name, min.toLocaleString(), max.toLocaleString(), avg.toFixed(2), sum.toLocaleString()];
            }),
        );
    }

    // Categorical summary
    const catCols = cols.filter(c => !numericCols.includes(c));
    if (catCols.length > 0) {
        addText('CATEGORICAL SUMMARY', { size: 8, bold: true, color: C.muted });
        addGap(6);
        addAutoTable(
            [['Column', 'Unique Values', 'Top Value', 'Nulls']],
            catCols.map(c => {
                const vals = rows.map(r => r[c.name]).filter(v => v !== null && v !== undefined);
                const uniqueCount = new Set(vals.map(String)).size;
                const nullCount = rows.length - vals.length;
                const freq = new Map<string, number>();
                vals.forEach(v => freq.set(String(v), (freq.get(String(v)) ?? 0) + 1));
                const topValue = [...freq.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? '';
                return [c.name, String(uniqueCount), topValue, nullCount > 0 ? String(nullCount) : '—'];
            }),
        );
    }

    // Data preview (first 10 rows)
    if (rows.length > 0 && cols.length > 0) {
        addText('DATA PREVIEW', { size: 8, bold: true, color: C.muted });
        addGap(6);
        const previewRows = rows.slice(0, 10);
        addAutoTable(
            [cols.map(c => c.name)],
            previewRows.map(row => cols.map(c => str(row[c.name]))),
        );
        if (rows.length > 10) {
            addText(`+ ${rows.length - 10} more rows`, { size: 8, color: C.muted });
            addGap(4);
        }
    }

    // SQL
    if (artifact.sql) {
        addGap(8);
        addText('SQL', { size: 8, bold: true, color: C.muted });
        addGap(4);
        doc.setFillColor(245, 245, 245);
        const sqlLines = doc.splitTextToSize(artifact.sql, contentWidth - 16);
        const sqlH = sqlLines.length * 10 + 12;
        if (y + sqlH > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
        }
        doc.roundedRect(margin, y, contentWidth, sqlH, 4, 4, 'F');
        doc.setFontSize(7);
        doc.setFont('courier', 'normal');
        doc.setTextColor(...C.fg);
        doc.text(sqlLines, margin + 8, y + 10);
        y += sqlH + 8;
    }

    // Footer
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const pageCount = (doc as any).internal.getNumberOfPages ? (doc as any).internal.getNumberOfPages() : (doc as any).internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(...C.muted);
        doc.text('Resona AI · Schema Weaver Data Explorer', margin, doc.internal.pageSize.getHeight() - 20);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, doc.internal.pageSize.getHeight() - 20, { align: 'right' });
    }

    doc.save(`${toFilename(reportTitle)}_executive.pdf`);
}
