// =============================================================================
// PPTX Report Builder — generates PowerPoint from artifact data using pptxgenjs
// Lazy-loaded to avoid bloating the initial bundle.
// =============================================================================

import type { AgentArtifact } from '@/hooks/useAIAgent';

/** Sanitize title into a filename stem. */
function toFilename(title: string): string {
    return (title || 'report')
        .replace(/[^a-zA-Z0-9_\- ]/g, '')
        .replace(/\s+/g, '_')
        .slice(0, 60);
}

const str = (v: unknown): string => (v === null || v === undefined ? '' : String(v));

// ─── Shared styles ───────────────────────────────────────────────────────────

const FONT = 'Segoe UI';
const COLORS = {
    title: '18181B',
    body: '3F3F46',
    muted: '71717A',
    accent: '2563EB',
    green: '16A34A',
    amber: 'D97706',
    red: 'DC2626',
    headerBg: 'F1F1F1',
    white: 'FFFFFF',
};

type PptxSlide = any; // Fallback since pptxgenjs types can be tricky with lazy loading

function addTitleSlide(pptx: import('pptxgenjs').default, title: string) {
    const slide = pptx.addSlide();
    slide.addText(title, { x: 0.6, y: 1.8, w: 8.8, h: 1, fontSize: 28, fontFace: FONT, bold: true, color: COLORS.title });
    slide.addText(`Generated by Resona AI · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`, {
        x: 0.6, y: 2.8, w: 8.8, h: 0.4, fontSize: 10, fontFace: FONT, color: COLORS.muted,
    });
    slide.addText('Schema Weaver Data Explorer', { x: 0.6, y: 5, w: 8.8, h: 0.3, fontSize: 8, fontFace: FONT, color: COLORS.muted });
}

function addFooter(slide: PptxSlide) {
    slide.addText('Resona AI · Schema Weaver', { x: 0.5, y: 5.1, w: 4, h: 0.25, fontSize: 7, fontFace: FONT, color: COLORS.muted });
}

// ─── Table rows helper for pptxgenjs ─────────────────────────────────────────

type TableRow = Array<{ text: string; options?: Record<string, unknown> }>;

function makeTableRows(
    headers: string[],
    rows: string[][],
): TableRow[] {
    const headerRow: TableRow = headers.map(h => ({
        text: h,
        options: { bold: true, fontSize: 8, fontFace: FONT, color: COLORS.muted, fill: { color: COLORS.headerBg } },
    }));
    const dataRows: TableRow[] = rows.map(row =>
        row.map(cell => ({
            text: cell,
            options: { fontSize: 8, fontFace: FONT, color: COLORS.body },
        }))
    );
    return [headerRow, ...dataRows];
}

// ─── Builder ─────────────────────────────────────────────────────────────────

export async function exportPptx(artifact: AgentArtifact, title?: string): Promise<void> {
    const PptxGenJS = (await import('pptxgenjs')).default;
    const pptx = new PptxGenJS();

    pptx.layout = 'LAYOUT_WIDE';
    pptx.author = 'Resona AI';
    pptx.company = 'Schema Weaver';

    const artType = artifact.type as string;
    const reportTitle = title || artifact.title || artType.charAt(0).toUpperCase() + artType.slice(1) + ' Report';

    pptx.title = reportTitle;

    // Title slide
    addTitleSlide(pptx, reportTitle);

    // Content slide(s)
    switch (artType) {
        case 'stats': {
            const stats = artifact.stats ?? [];
            // Split stats into pages of 12
            const perPage = 12;
            for (let i = 0; i < stats.length; i += perPage) {
                const chunk = stats.slice(i, i + perPage);
                const slide = pptx.addSlide();
                slide.addText('Column Statistics', { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
                if (artifact.totalRows != null) {
                    slide.addText(`${artifact.totalRows.toLocaleString()} rows · ${stats.length} columns`, { x: 0.5, y: 0.7, w: 9, h: 0.25, fontSize: 9, fontFace: FONT, color: COLORS.muted });
                }
                const tableRows = makeTableRows(
                    ['Column', 'Type', 'Distinct', 'Null %', 'Min', 'Max', 'Avg', 'Flags'],
                    chunk.map(s => [
                        s.name, s.dataType, String(s.distinctCount),
                        s.nullPercent.toFixed(1) + '%', str(s.min), str(s.max),
                        s.avg !== null ? String(s.avg) : '',
                        [s.isPrimaryKey && 'PK', s.isIndexed && 'IDX'].filter(Boolean).join(', '),
                    ]),
                );
                slide.addTable(tableRows, { x: 0.5, y: 1.05, w: 12.3, colW: [1.8, 1.2, 0.8, 0.7, 1.5, 1.5, 1, 0.8], border: { pt: 0.5, color: 'E4E4E7' }, autoPage: true });
                addFooter(slide);
            }
            break;
        }

        case 'anomalies': {
            const anomalies = artifact.anomalies ?? [];
            const slide = pptx.addSlide();
            slide.addText('Anomaly Detection', { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
            slide.addText(`${artifact.totalAnomalies ?? anomalies.length} anomalies across ${artifact.scannedColumns ?? 0} columns`, { x: 0.5, y: 0.7, w: 9, h: 0.25, fontSize: 9, fontFace: FONT, color: COLORS.muted });
            if (anomalies.length > 0) {
                const tableRows = makeTableRows(
                    ['Column', 'Type', 'Severity', 'Count', 'Detail'],
                    anomalies.slice(0, 20).map(a => [a.column, a.type.replace(/_/g, ' '), a.severity.toUpperCase(), String(a.count), a.explanation]),
                );
                slide.addTable(tableRows, { x: 0.5, y: 1.05, w: 12.3, colW: [2, 2, 1, 0.8, 6.5], border: { pt: 0.5, color: 'E4E4E7' }, autoPage: true });
            }
            addFooter(slide);
            break;
        }

        case 'quality': {
            const score = artifact.score ?? 0;
            const scoreColor = score >= 80 ? COLORS.green : score >= 50 ? COLORS.amber : COLORS.red;
            const slide = pptx.addSlide();
            slide.addText('Data Quality Report', { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
            // Big score
            slide.addText(String(score), { x: 0.5, y: 1, w: 2, h: 1.2, fontSize: 48, fontFace: FONT, bold: true, color: scoreColor });
            slide.addText('/100', { x: 2.2, y: 1.5, w: 1, h: 0.5, fontSize: 14, fontFace: FONT, color: COLORS.muted });
            // Score bar
            slide.addShape('rect' as any, { x: 0.5, y: 2.3, w: 12.3, h: 0.12, fill: { color: COLORS.headerBg }, rectRadius: 0.06 });
            slide.addShape('rect' as any, { x: 0.5, y: 2.3, w: 12.3 * (score / 100), h: 0.12, fill: { color: scoreColor }, rectRadius: 0.06 });
            if (artifact.summary) {
                slide.addText(artifact.summary, { x: 0.5, y: 2.6, w: 12.3, h: 0.4, fontSize: 10, fontFace: FONT, color: COLORS.muted });
            }
            const issues = artifact.issues ?? [];
            if (issues.length > 0) {
                const tableRows = makeTableRows(
                    ['Severity', 'Column', 'Issue', 'Rows', 'Recommendation'],
                    issues.slice(0, 15).map(i => [i.severity.toUpperCase(), i.column, i.issueType.replace(/_/g, ' '), String(i.affectedRows), i.recommendation]),
                );
                slide.addTable(tableRows, { x: 0.5, y: 3.1, w: 12.3, colW: [1, 2, 2.5, 1, 5.8], border: { pt: 0.5, color: 'E4E4E7' }, autoPage: true });
            }
            addFooter(slide);
            break;
        }

        case 'joins': {
            const paths = artifact.paths ?? [];
            const slide = pptx.addSlide();
            slide.addText('Join Paths', { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
            slide.addText(`${paths.length} path${paths.length !== 1 ? 's' : ''} discovered`, { x: 0.5, y: 0.7, w: 9, h: 0.25, fontSize: 9, fontFace: FONT, color: COLORS.muted });
            if (paths.length > 0) {
                const tableRows = makeTableRows(
                    ['From', 'Column', '', 'To', 'Column', 'Type', 'Confidence'],
                    paths.map(p => [p.from, p.fromColumn, '→', p.to, p.toColumn, p.joinType === 'foreign_key' ? 'FK' : 'Heuristic', Math.round(p.confidence * 100) + '%']),
                );
                slide.addTable(tableRows, { x: 0.5, y: 1.05, w: 12.3, colW: [2, 2, 0.4, 2, 2, 1.2, 1], border: { pt: 0.5, color: 'E4E4E7' } });
            }
            addFooter(slide);
            break;
        }

        case 'metrics': {
            const slide = pptx.addSlide();
            slide.addText('Inferred Metrics', { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
            let yPos = 1;
            const groups = [
                { items: artifact.identifiers ?? [], label: 'IDENTIFIERS', color: '7C3AED' },
                { items: artifact.dimensions ?? [], label: 'DIMENSIONS', color: COLORS.accent },
                { items: artifact.measures ?? [], label: 'MEASURES', color: COLORS.green },
                { items: artifact.timestamps ?? [], label: 'TIMESTAMPS', color: COLORS.amber },
            ];
            for (const g of groups) {
                if (g.items.length === 0) continue;
                slide.addText(g.label, { x: 0.5, y: yPos, w: 9, h: 0.25, fontSize: 8, fontFace: FONT, bold: true, color: COLORS.muted });
                yPos += 0.3;
                slide.addText(g.items.join('   ·   '), { x: 0.5, y: yPos, w: 12.3, h: 0.35, fontSize: 12, fontFace: FONT, color: g.color });
                yPos += 0.5;
            }
            addFooter(slide);
            break;
        }

        default: {
            // Table artifact — split into pages of 20 rows
            const rows = artifact.rows ?? [];
            const cols = artifact.columns ?? [];
            if (rows.length > 0 && cols.length > 0) {
                const perPage = 20;
                for (let i = 0; i < rows.length; i += perPage) {
                    const chunk = rows.slice(i, i + perPage);
                    const slide = pptx.addSlide();
                    slide.addText(reportTitle, { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
                    slide.addText(`${rows.length} rows · ${cols.length} columns${i > 0 ? ` (rows ${i + 1}–${Math.min(i + perPage, rows.length)})` : ''}`, {
                        x: 0.5, y: 0.7, w: 9, h: 0.25, fontSize: 9, fontFace: FONT, color: COLORS.muted,
                    });
                    const tableRows = makeTableRows(
                        cols.map(c => c.name),
                        chunk.map(row => cols.map(c => str(row[c.name]))),
                    );
                    const colW = cols.map(() => Math.min(12.3 / cols.length, 3));
                    slide.addTable(tableRows, { x: 0.5, y: 1.05, w: 12.3, colW, border: { pt: 0.5, color: 'E4E4E7' }, autoPage: true });
                    addFooter(slide);
                }
            }
            break;
        }
    }

    // SQL slide
    if (artifact.sql) {
        const slide = pptx.addSlide();
        slide.addText('SQL Query', { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 16, fontFace: FONT, bold: true, color: COLORS.title });
        slide.addShape('rect' as any, { x: 0.5, y: 0.9, w: 12.3, h: 4, fill: { color: 'F5F5F5' }, rectRadius: 0.1 });
        slide.addText(artifact.sql, { x: 0.7, y: 1, w: 11.9, h: 3.8, fontSize: 9, fontFace: 'Courier New', color: COLORS.body, valign: 'top' });
        addFooter(slide);
    }

    await pptx.writeFile({ fileName: `${toFilename(reportTitle)}.pptx` });
}
